### ISSUE TITLE
Open tab always jumps to the right

### ISSUE THREAD

**Issue by timohausmann** [marcusviar/vscode-sort-tabs#1]
The plugin worked really well until today. But now the active tab always jumps to the very right which breaks the sorting by name and grouping by filetype. I restarted VSCode but the problem persists.

![Screen Recording 2020-10-11 at 17 48 11](https://user-images.githubusercontent.com/2311113/95683413-55d25580-0beb-11eb-8116-7b222ea513e7.gif)

**Comment by marcusviar** [comment]
Sorry for my late reply. Please try closing all your tabs, then restart VSCode, then reopen your tabs.

The extension needs VSCode to start with no tabs open when VSCode is restarted. This is a limitation because the extension API won't allow it to get a list of all open files. Instead, the extension keeps a record of text based files as you open them.

**Comment by timohausmann** [comment]
I'm sorry but closing all tabs and restarting VSCode does not help. I even disabled the Welcome-Tab.
(Tested on macOS)

I'm wondering because the plugin was working in the past.

**Comment by marcusviar** [comment]
Unfortunately I don't currently have a fix for the problem. The VSCode extension API is very limited in what it allows extensions to access in regards to open tabs. During testing I kept finding more and more problems with it because of the lack of information available via the API, hence all the known issues in the readme.

I've actually quit using the extension myself because new problems kept popping up. If the extension API is ever extended to include more information about tabs; I will write an update for the extension. For now I find it more convenient to limit the amount of tabs open in VSCode to make it easier and quicker to find the open file I'm looking for.

You can limit the amount of open tabs allowed via VSCode settings: Workbench > Editor > Limit.

![vscode_tab_limit](https://user-images.githubusercontent.com/36222663/98199713-768f8180-1ef1-11eb-88b0-04509d17421e.png)

**Comment by timohausmann** [comment]
Okay, thanks for your feedback. The plugin was a very nice idea though :-)
